@echo Barev Dzez, ev bari galust MOSO system....
@echo launching GUI...
@echo off
@REM cd C:\Users\Armne\OneDrive\Documents\Code\Python
c:\Users\Armne\AppData\Local\Programs\Python\Python39\python.exe moso.pyw