@echo Barev Dzez, ev bari galust MOSO-i system....
@echo launching Server...
@echo off
cd C:\Users\Armne\OneDrive\Documents\Code\Python
start c:\Users\Armne\AppData\Local\Programs\Python\Python39\python.exe app.py